export type {
  AppConfig,
  OAuthConfig,
  GoogleOAuthConfig,
  AutoAuthConfig,
  RoleConfig,
  RoleConnectors,
  ConnectorConfig,
  ApiTier,
  AccountToken,
  TokenStore,
} from "./config.js";

export type {
  MailMessage,
  MailMessageFull,
  MailAttachment,
  CalendarEvent,
  CalendarInfo,
  CalendarEventInput,
  RemoteContact,
  ContactInput,
  Conversation,
  ChatMessage,
  FileResult,
  MailConnector,
  CalendarConnector,
  ContactConnector,
  MessengerConnector,
  FileConnector,
} from "./connectors.js";
